apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-pv
spec:
  capacity:
    storage: 5Ti        # match values.yaml
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-storage
  local:
    path: /mnt/hdd/minio   # your HDD mount point
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - cdhc-server-precision-3640-tower

